export const routes = {
	home: "/",
	login: "/login",
	cars: {
		list: "/cars",
		create: "/cars",
		update: (id: string) => `/cars/${id}`,
		delete: (id: string) => `/cars/${id}`,
		getById: (id: string) => `/cars/${id}`,
	},
	clients: {
		list: "/clients",
		create: "/clients",
		update: (id: string) => `/clients/${id}`,
		delete: (id: string) => `/clients/${id}`,
		getById: (id: string) => `/clients/${id}`,
	},
	drivers: {
		list: "/drivers",
		create: "/drivers",
		update: (id: string) => `/drivers/${id}`,
		delete: (id: string) => `/drivers/${id}`,
		getById: (id: string) => `/drivers/${id}`,
	},
	jobs: {
		list: "/jobs",
		create: "/jobs",
		update: (id: string) => `/jobs/${id}`,
		delete: (id: string) => `/jobs/${id}`,
	},
	orders: {
		list: "/orders",
		create: "/orders",
		createBatch: "/orders/batch",
		update: (id: string) => `/orders/${id}`,
		delete: (id: string) => `/orders/${id}`,
	},
	payments: {
		list: "/payments",
		create: "/payments",
		update: (id: string) => `/payments/${id}`,
		delete: (id: string) => `/payments/${id}`,
	},
	products: {
		list: "/products",
		create: "/products",
		update: (id: string) => `/products/${id}`,
		delete: (id: string) => `/products/${id}`,
	},
	salesperson: {
		list: "/salesperson",
		create: "/salesperson",
		update: (id: string) => `/salesperson/${id}`,
		delete: (id: string) => `/salesperson/${id}`,
		getById: (id: string) => `/salesperson/${id}`,
	},
	users: {
		list: "/users",
		create: "/users",
		update: (id: string) => `/users/${id}`,
		delete: (id: string) => `/users/${id}`,
		getById: (id: string) => `/users/${id}`,
		getDriverList: "/users/driver-list",
	},
}
